# ================================
# STAGE 1: Build de Vite
# ================================
FROM node:24-alpine AS builder

# Envía las variables desde docker-compose (build.args)
ARG VITE_API_BASE_URL
ARG VITE_POWERBI_REPORT_URL

# Exportarlas como variables de entorno dentro del build
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_POWERBI_REPORT_URL=$VITE_POWERBI_REPORT_URL

# Crear directorio
WORKDIR /app

# Copiar archivos
COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Construir frontend
RUN npm run build


# ================================
# STAGE 2: Servir con Nginx
# ================================
FROM nginx:stable-alpine

# Copiar artefactos de build
COPY --from=builder /app/dist /usr/share/nginx/html

# Configuración custom de nginx (opcional)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]