FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG VITE_AAD_CLIENT_ID
ARG VITE_AAD_TENANT_ID
ARG VITE_API_BASE_URL
ARG VITE_POWERBI_REPORT_URL
RUN echo "VITE_AAD_CLIENT_ID=$VITE_AAD_CLIENT_ID"        >  .env.production && \
    echo "VITE_AAD_TENANT_ID=$VITE_AAD_TENANT_ID"        >> .env.production && \
    echo "VITE_API_BASE_URL=$VITE_API_BASE_URL"          >> .env.production && \
    echo "VITE_POWERBI_REPORT_URL=$VITE_POWERBI_REPORT_URL" >> .env.production


RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]